/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       scd4x
 * Model-Version: 2.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scd4x_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"
#include "itm.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

#define ROUND(x) ((int32_t)((x) + 0.5))

static uint8_t communication_buffer[9] = {0};

static uint8_t _i2c_address;
static bool _measurement_running = false;

typedef struct {
    const scd4x_runtime_t* runtime;
    scd4x_runtime_fault_cause_t cause;
    int16_t error;
    uint32_t hal_state;
    uint32_t hal_error;
    uint32_t repeat_count;
    bool has_active_fault;
    bool line_open;
} scd4x_itm_fault_log_state_t;

static bool g_scd4x_itm_short_log_enabled = true;
static scd4x_itm_fault_log_state_t g_scd4x_itm_fault_log_state = {0};

static int16_t scd4x_runtime_lock(const scd4x_runtime_t* runtime) {
    if ((runtime == NULL) || (runtime->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    if (osMutexAcquire(runtime->i2c_mutex, osWaitForever) != osOK) {
        return NOT_IMPLEMENTED_ERROR;
    }

    return NO_ERROR;
}

static void scd4x_runtime_unlock(const scd4x_runtime_t* runtime) {
    if ((runtime != NULL) && (runtime->i2c_mutex != NULL)) {
        (void)osMutexRelease(runtime->i2c_mutex);
    }
}

static void scd4x_runtime_update_diag(scd4x_runtime_t* runtime) {
    if ((runtime == NULL) || (runtime->i2c_handle == NULL)) {
        return;
    }

    runtime->i2c_hal_state = (uint32_t)HAL_I2C_GetState(runtime->i2c_handle);
    runtime->i2c_hal_error = HAL_I2C_GetError(runtime->i2c_handle);
}

static scd4x_runtime_fault_cause_t scd4x_runtime_classify_fault(
    const scd4x_runtime_t* runtime, int16_t error) {
    uint32_t hal_error = 0U;

    if (runtime != NULL) {
        hal_error = runtime->i2c_hal_error;
    }

    if (error == NO_ERROR) {
        return SCD4X_RUNTIME_FAULT_NONE;
    }

    if ((error == (int16_t)HAL_TIMEOUT) || ((hal_error & HAL_I2C_ERROR_TIMEOUT) != 0U)) {
        return SCD4X_RUNTIME_FAULT_TIMEOUT;
    }

    if ((error == (int16_t)HAL_BUSY)) {
        return SCD4X_RUNTIME_FAULT_BUSY;
    }

    if ((hal_error & HAL_I2C_ERROR_AF) != 0U) {
        return SCD4X_RUNTIME_FAULT_NO_ACK;
    }

    if ((hal_error & (HAL_I2C_ERROR_BERR | HAL_I2C_ERROR_ARLO | HAL_I2C_ERROR_OVR)) != 0U) {
        return SCD4X_RUNTIME_FAULT_BUS;
    }

    if (error == CRC_ERROR) {
        return SCD4X_RUNTIME_FAULT_CRC;
    }

    if (error == (int16_t)HAL_ERROR) {
        return SCD4X_RUNTIME_FAULT_NO_ACK;
    }

    return SCD4X_RUNTIME_FAULT_UNKNOWN;
}

static void scd4x_runtime_notify(const scd4x_runtime_t* runtime,
                                 scd4x_runtime_event_t event) {
    if ((runtime != NULL) && (runtime->on_event != NULL)) {
        runtime->on_event(runtime, event, runtime->on_event_context);
    }
}

static const char* scd4x_runtime_fault_cause_to_text(
    scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NONE:
            return "NONE";
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "NO_ACK";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "TIMEOUT";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "BUS_ERROR";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "CRC_ERROR";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "BUSY";
        default:
            return "UNKNOWN";
    }
}

static const char* scd4x_runtime_error_to_text(int16_t error) {
    switch (error) {
        case NO_ERROR:
            return "NO_ERROR";
        case CRC_ERROR:
            return "CRC_ERROR";
        case I2C_BUS_ERROR:
            return "I2C_BUS_ERROR";
        case I2C_NACK_ERROR:
            return "I2C_NACK_ERROR";
        case BYTE_NUM_ERROR:
            return "BYTE_NUM_ERROR";
        default:
            break;
    }

    if (error == (int16_t)HAL_ERROR) {
        return "HAL_ERROR";
    }
    if (error == (int16_t)HAL_BUSY) {
        return "HAL_BUSY";
    }
    if (error == (int16_t)HAL_TIMEOUT) {
        return "HAL_TIMEOUT";
    }

    return "UNMAPPED_ERROR";
}

static const char* scd4x_runtime_i2c_state_to_text(uint32_t state) {
    switch ((HAL_I2C_StateTypeDef)state) {
        case HAL_I2C_STATE_RESET:
            return "RESET";
        case HAL_I2C_STATE_READY:
            return "READY";
        case HAL_I2C_STATE_BUSY:
            return "BUSY";
        case HAL_I2C_STATE_BUSY_TX:
            return "BUSY_TX";
        case HAL_I2C_STATE_BUSY_RX:
            return "BUSY_RX";
        case HAL_I2C_STATE_LISTEN:
            return "LISTEN";
        case HAL_I2C_STATE_BUSY_TX_LISTEN:
            return "BUSY_TX_LISTEN";
        case HAL_I2C_STATE_BUSY_RX_LISTEN:
            return "BUSY_RX_LISTEN";
        case HAL_I2C_STATE_ABORT:
            return "ABORT";
        case HAL_I2C_STATE_TIMEOUT:
            return "TIMEOUT";
        case HAL_I2C_STATE_ERROR:
            return "ERROR";
        default:
            return "UNKNOWN";
    }
}

static void scd4x_runtime_print_i2c_error_flags(uint32_t hal_error) {
    bool first = true;

    if (hal_error == HAL_I2C_ERROR_NONE) {
        itm_print("NONE");
        return;
    }

    if ((hal_error & HAL_I2C_ERROR_BERR) != 0U) {
        itm_print("BERR");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_ARLO) != 0U) {
        itm_print(first ? "ARLO" : "|ARLO");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_AF) != 0U) {
        itm_print(first ? "NACK(AF)" : "|NACK(AF)");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_OVR) != 0U) {
        itm_print(first ? "OVR" : "|OVR");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_DMA) != 0U) {
        itm_print(first ? "DMA" : "|DMA");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_TIMEOUT) != 0U) {
        itm_print(first ? "TIMEOUT" : "|TIMEOUT");
        first = false;
    }
    if ((hal_error & HAL_I2C_ERROR_SIZE) != 0U) {
        itm_print(first ? "SIZE" : "|SIZE");
        first = false;
    }

    if (first) {
        itm_print("UNKNOWN_FLAGS");
    }
}

static const char* scd4x_runtime_fault_hint(scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "check sensor power/address/wiring";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "check SDA/SCL disconnected or bus stuck";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "check noise/short on I2C lines";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "data corrupted, check cable/noise";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "bus busy, check shared bus access";
        default:
            return "check sensor connection";
    }
}

static const char* scd4x_runtime_bus_to_text(const scd4x_runtime_t* runtime) {
    if ((runtime == NULL) || (runtime->i2c_handle == NULL) ||
        (runtime->i2c_handle->Instance == NULL)) {
        return "I2C";
    }

    if (runtime->i2c_handle->Instance == I2C1) {
        return "I2C1";
    }
    if (runtime->i2c_handle->Instance == I2C2) {
        return "I2C2";
    }

    return "I2C";
}

static const char* scd4x_runtime_fault_simple_text(
    scd4x_runtime_fault_cause_t cause) {
    switch (cause) {
        case SCD4X_RUNTIME_FAULT_NO_ACK:
            return "khong giao tiep duoc voi sensor (NACK)";
        case SCD4X_RUNTIME_FAULT_TIMEOUT:
            return "timeout bus, sensor khong phan hoi";
        case SCD4X_RUNTIME_FAULT_BUS:
            return "loi truyen thong bus";
        case SCD4X_RUNTIME_FAULT_CRC:
            return "du lieu loi (CRC), giao tiep khong on dinh";
        case SCD4X_RUNTIME_FAULT_BUSY:
            return "bus dang ban";
        default:
            return "mat ket noi sensor";
    }
}

void scd4x_runtime_default_itm_set_short_log(bool enable) {
    g_scd4x_itm_short_log_enabled = enable;
    g_scd4x_itm_fault_log_state.runtime = NULL;
    g_scd4x_itm_fault_log_state.repeat_count = 0U;
    g_scd4x_itm_fault_log_state.has_active_fault = false;
    g_scd4x_itm_fault_log_state.line_open = false;
}

void scd4x_runtime_default_itm_event_handler(const scd4x_runtime_t* runtime,
                                             scd4x_runtime_event_t event,
                                             void* user_context) {
    bool same_fault;

    (void)user_context;

    if (runtime == NULL) {
        return;
    }

    switch (event) {
        case SCD4X_RUNTIME_EVENT_FAULT:
            same_fault = g_scd4x_itm_fault_log_state.has_active_fault &&
                         (g_scd4x_itm_fault_log_state.runtime == runtime) &&
                         (g_scd4x_itm_fault_log_state.cause == runtime->fault_cause) &&
                         (g_scd4x_itm_fault_log_state.error == runtime->error) &&
                         (g_scd4x_itm_fault_log_state.hal_state == runtime->i2c_hal_state) &&
                         (g_scd4x_itm_fault_log_state.hal_error == runtime->i2c_hal_error);

            if (same_fault) {
                g_scd4x_itm_fault_log_state.repeat_count++;
            } else {
                g_scd4x_itm_fault_log_state.runtime = runtime;
                g_scd4x_itm_fault_log_state.cause = runtime->fault_cause;
                g_scd4x_itm_fault_log_state.error = runtime->error;
                g_scd4x_itm_fault_log_state.hal_state = runtime->i2c_hal_state;
                g_scd4x_itm_fault_log_state.hal_error = runtime->i2c_hal_error;
                g_scd4x_itm_fault_log_state.repeat_count = 1U;
                g_scd4x_itm_fault_log_state.has_active_fault = true;
            }

            if (g_scd4x_itm_short_log_enabled && same_fault) {
                break;
            }

            if (g_scd4x_itm_short_log_enabled) {
                itm_print("[SCD41][ERR] ");
                itm_print(scd4x_runtime_bus_to_text(runtime));
                itm_print(": ");
                itm_print(scd4x_runtime_fault_simple_text(runtime->fault_cause));
                itm_print(". Kiem tra day SDA/SCL va nguon sensor.\r\n");
                break;
            }

            itm_print("[SCD41][FAULT] cause=");
            itm_print(scd4x_runtime_fault_cause_to_text(runtime->fault_cause));
            itm_print("(");
            itm_put_int((int)runtime->fault_cause);
            itm_print(")");
            itm_print(", err=");
            itm_print(scd4x_runtime_error_to_text(runtime->error));
            itm_print("(");
            itm_put_int((int)runtime->error);
            itm_print(")");
            itm_print(", state=");
            itm_print(scd4x_runtime_i2c_state_to_text(runtime->i2c_hal_state));
            itm_print("(");
            itm_put_int((int)runtime->i2c_hal_state);
            itm_print(")");
            itm_print(", hal_error=");
            scd4x_runtime_print_i2c_error_flags(runtime->i2c_hal_error);
            itm_print("(");
            itm_put_int((int)runtime->i2c_hal_error);
            itm_print(")");
            itm_print(", hint=");
            itm_print(scd4x_runtime_fault_hint(runtime->fault_cause));
            itm_print(", count=");
            itm_put_int((int)g_scd4x_itm_fault_log_state.repeat_count);
            itm_print("\r\n");
            break;

        case SCD4X_RUNTIME_EVENT_RECOVERED:
            g_scd4x_itm_fault_log_state.has_active_fault = false;
            g_scd4x_itm_fault_log_state.repeat_count = 0U;
            itm_print("[SCD41] ");
            itm_print(scd4x_runtime_bus_to_text(runtime));
            itm_print(": da ket noi lai sensor\r\n");
            break;

        case SCD4X_RUNTIME_EVENT_RESTART_ATTEMPT:
            if (!g_scd4x_itm_short_log_enabled) {
                itm_print("[SCD41] retry start periodic measurement\r\n");
            }
            break;

        default:
            break;
    }
}

void scd4x_runtime_set_event_callback(scd4x_runtime_t* runtime,
                                      scd4x_runtime_event_callback_t callback,
                                      void* user_context) {
    if (runtime == NULL) {
        return;
    }

    runtime->on_event = callback;
    runtime->on_event_context = user_context;
}

void scd4x_init(uint8_t i2c_address) {
    _i2c_address = i2c_address;
}

void scd4x_runtime_init(scd4x_runtime_t* runtime,
                        I2C_HandleTypeDef* i2c_handle,
                        osMutexId_t i2c_mutex) {
    if (runtime == NULL) {
        return;
    }

    runtime->i2c_handle = i2c_handle;
    runtime->i2c_mutex = i2c_mutex;
    runtime->i2c_address = SCD41_I2C_ADDR_62;
    runtime->co2 = 0;
    runtime->temperature_m_deg_c = 0;
    runtime->humidity_m_percent_rh = 0;
    runtime->data_ready = false;
    runtime->error = NO_ERROR;
    runtime->i2c_hal_state = 0U;
    runtime->i2c_hal_error = 0U;
    runtime->consecutive_error_count = 0U;
    runtime->total_error_count = 0U;
    runtime->restart_after_failures = 5U;
    runtime->fault_active = false;
    runtime->fault_cause = SCD4X_RUNTIME_FAULT_NONE;
    runtime->on_event = NULL;
    runtime->on_event_context = NULL;

    sensirion_i2c_hal_set_handle(i2c_handle);
    sensirion_i2c_hal_set_mutex(i2c_mutex);
    scd4x_init(runtime->i2c_address);
    scd4x_runtime_update_diag(runtime);
}

int16_t scd4x_runtime_start_periodic_measurement(scd4x_runtime_t* runtime) {
    if ((runtime == NULL) || (runtime->i2c_handle == NULL) ||
        (runtime->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    runtime->error = scd4x_runtime_lock(runtime);
    if (runtime->error != NO_ERROR) {
        return runtime->error;
    }

    sensirion_i2c_hal_set_handle(runtime->i2c_handle);
    sensirion_i2c_hal_set_mutex(runtime->i2c_mutex);
    scd4x_init(runtime->i2c_address);

    runtime->error = scd4x_start_periodic_measurement();
    scd4x_runtime_unlock(runtime);

    scd4x_runtime_update_diag(runtime);
    if (runtime->error == NO_ERROR) {
        runtime->consecutive_error_count = 0U;
    }

    return runtime->error;
}

int16_t scd4x_runtime_read_if_ready(scd4x_runtime_t* runtime) {
    if ((runtime == NULL) || (runtime->i2c_handle == NULL) ||
        (runtime->i2c_mutex == NULL)) {
        return NOT_IMPLEMENTED_ERROR;
    }

    runtime->error = scd4x_runtime_lock(runtime);
    if (runtime->error != NO_ERROR) {
        return runtime->error;
    }

    sensirion_i2c_hal_set_handle(runtime->i2c_handle);
    sensirion_i2c_hal_set_mutex(runtime->i2c_mutex);

    runtime->error = scd4x_get_data_ready_status(&runtime->data_ready);
    if (runtime->error != NO_ERROR) {
        scd4x_runtime_unlock(runtime);
        scd4x_runtime_update_diag(runtime);
        return runtime->error;
    }

    if (!runtime->data_ready) {
        scd4x_runtime_unlock(runtime);
        scd4x_runtime_update_diag(runtime);
        return NO_ERROR;
    }

    runtime->error = scd4x_read_measurement(&runtime->co2,
                                            &runtime->temperature_m_deg_c,
                                            &runtime->humidity_m_percent_rh);
    scd4x_runtime_unlock(runtime);
    scd4x_runtime_update_diag(runtime);
    return runtime->error;
}

bool scd4x_runtime_poll(scd4x_runtime_t* runtime) {
    int16_t restart_error;
    bool fault_was_active;

    if (runtime == NULL) {
        return false;
    }

    fault_was_active = runtime->fault_active;
    runtime->error = scd4x_runtime_read_if_ready(runtime);
    if (runtime->error == NO_ERROR) {
        /* After a disconnect/power-loss fault, force start command once bus is alive again. */
        if (fault_was_active && !runtime->data_ready) {
            _measurement_running = false;
            (void)scd4x_runtime_start_periodic_measurement(runtime);
            runtime->error = scd4x_runtime_read_if_ready(runtime);
        }

        if (runtime->error != NO_ERROR) {
            runtime->total_error_count++;
            runtime->consecutive_error_count++;
            runtime->fault_cause = scd4x_runtime_classify_fault(runtime, runtime->error);
            runtime->fault_active = true;
            scd4x_runtime_notify(runtime, SCD4X_RUNTIME_EVENT_FAULT);
            return false;
        }

        runtime->consecutive_error_count = 0U;
        runtime->fault_cause = SCD4X_RUNTIME_FAULT_NONE;

        if (runtime->fault_active) {
            runtime->fault_active = false;
            scd4x_runtime_notify(runtime, SCD4X_RUNTIME_EVENT_RECOVERED);
        }

        return runtime->data_ready;
    }

    runtime->total_error_count++;
    runtime->consecutive_error_count++;
    runtime->fault_cause = scd4x_runtime_classify_fault(runtime, runtime->error);

    if (runtime->fault_cause != SCD4X_RUNTIME_FAULT_CRC) {
        _measurement_running = false;
    }

    if (!runtime->fault_active) {
        runtime->fault_active = true;
        scd4x_runtime_notify(runtime, SCD4X_RUNTIME_EVENT_FAULT);
    } else {
        /* Notify again on each fault to allow caller-specific policies. */
        scd4x_runtime_notify(runtime, SCD4X_RUNTIME_EVENT_FAULT);
    }

    if ((runtime->restart_after_failures > 0U) &&
        ((runtime->consecutive_error_count % runtime->restart_after_failures) == 0U)) {
        scd4x_runtime_notify(runtime, SCD4X_RUNTIME_EVENT_RESTART_ATTEMPT);
        restart_error = scd4x_runtime_start_periodic_measurement(runtime);
        if (restart_error == NO_ERROR) {
            runtime->consecutive_error_count = 0U;
        }
    }

    return false;
}

uint16_t scd4x_signal_co2_concentration(uint16_t raw_co2_concentration) {
    uint16_t co2_concentration = 0;
    co2_concentration = raw_co2_concentration;
    return co2_concentration;
}

uint32_t scd4x_signal_ambient_pressure(uint16_t raw_ambient_pressure) {
    uint32_t ambient_pressure = 0;
    ambient_pressure = (uint32_t)raw_ambient_pressure * 100;
    return ambient_pressure;
}

int16_t scd4x_set_ambient_pressure(uint32_t ambient_pressure) {
    int16_t local_error = 0;
    uint16_t raw_ambient_pressure = (uint16_t)ROUND(ambient_pressure / 100.0);
    local_error = scd4x_set_ambient_pressure_raw(raw_ambient_pressure);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t scd4x_get_ambient_pressure(uint32_t* a_ambient_pressure) {
    uint16_t raw_ambient_pressure = 0;
    int16_t local_error = 0;
    local_error = scd4x_get_ambient_pressure_raw(&raw_ambient_pressure);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_ambient_pressure = scd4x_signal_ambient_pressure(raw_ambient_pressure);

    return local_error;
}

int16_t scd4x_get_data_ready_status(bool* arg_0) {
    uint16_t data_ready_status = 0;
    int16_t local_error = 0;
    local_error = scd4x_get_data_ready_status_raw(&data_ready_status);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *arg_0 = (data_ready_status & 2047) != 0;
    ;
    return local_error;
}

int16_t scd4x_get_sensor_variant(scd4x_sensor_variant* a_sensor_variant) {
    scd4x_sensor_variant ret_val = SCD4X_SENSOR_VARIANT_MASK;
    uint16_t raw_sensor_variant = 0;
    uint16_t my_sensor_variant = 0;
    int16_t local_error = 0;
    ret_val = SCD4X_SENSOR_VARIANT_MASK;
    uint16_t mask = (uint16_t)(ret_val);
    local_error = scd4x_get_sensor_variant_raw(&raw_sensor_variant);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    my_sensor_variant = (uint16_t)(raw_sensor_variant & mask);
    if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD40)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD40;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD41)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD41;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD42)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD42;
    } else if (my_sensor_variant == (uint16_t)(SCD4X_SENSOR_VARIANT_SCD43)) {
        ret_val = SCD4X_SENSOR_VARIANT_SCD43;
    }
    *a_sensor_variant = ret_val;
    return local_error;
}

int16_t scd4x_start_periodic_measurement() {
    if (_measurement_running) {
        return NO_ERROR;
    }

    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x21b1);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }

    //in ra itmconsole----------------------------------------------------------------------------------------------------------------
    itm_print("[SCD41] START_PERIODIC_MEASUREMENT");
    itm_print("\r\n");
    //--------------------------------------------------------------------------------------------------------------------------------


    _measurement_running = true;
    return local_error;
}

int16_t scd4x_read_measurement_raw(uint16_t* co2_concentration,
                                   uint16_t* temperature,
                                   uint16_t* relative_humidity) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xec05);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *co2_concentration = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    *temperature = sensirion_common_bytes_to_uint16_t(&buffer_ptr[2]);
    *relative_humidity = sensirion_common_bytes_to_uint16_t(&buffer_ptr[4]);
    return local_error;
}

int16_t scd4x_read_measurement(uint16_t* co2, int32_t* temperature_m_deg_c,
                               int32_t* humidity_m_percent_rh) {
    int16_t error;
    uint16_t temperature;
    uint16_t humidity;
    error = scd4x_read_measurement_raw(co2, &temperature, &humidity);
    if (error) {
        return error;
    }
    *temperature_m_deg_c = ((21875 * (int32_t)temperature) >> 13) - 45000;
    *humidity_m_percent_rh = ((12500 * (int32_t)humidity) >> 13);
    return NO_ERROR;
}

int16_t scd4x_stop_periodic_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3f86);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(500 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_set_temperature_offset_raw(uint16_t offset_temperature) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x241d);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, offset_temperature);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_temperature_offset_raw(uint16_t* offset_temperature) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2318);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *offset_temperature = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_sensor_altitude(uint16_t sensor_altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2427);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, sensor_altitude);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_sensor_altitude(uint16_t* sensor_altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2322);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_altitude = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_ambient_pressure_raw(uint16_t ambient_pressure) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe000);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, ambient_pressure);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_ambient_pressure_raw(uint16_t* ambient_pressure) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe000);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *ambient_pressure = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_perform_forced_recalibration(uint16_t target_co2_concentration,
                                           uint16_t* frc_correction) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x362f);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, target_co2_concentration);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(400 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *frc_correction = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_enabled(uint16_t asc_enabled) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2416);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_enabled);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    if (asc_enabled == 1) {
            itm_print("ASC has been ENABLED successfully\n");
        } else {
            itm_print("ASC has been DISABLED successfully\n");
        }
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_enabled(uint16_t* asc_enabled) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2313);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_enabled = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_target(uint16_t asc_target) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x243a);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_target);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_target(uint16_t* asc_target) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x233f);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_target = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_start_low_power_periodic_measurement() {
    if (_measurement_running) {
        return NO_ERROR;
    }

    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x21ac);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    _measurement_running = true;
    return local_error;
}

int16_t scd4x_get_data_ready_status_raw(uint16_t* data_ready_status) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0xe4b8);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *data_ready_status = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_persist_settings() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3615);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(800 * 1000);
    return local_error;
}

int16_t scd4x_get_serial_number(uint16_t* serial_number,
                                uint16_t serial_number_size) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3682);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)serial_number,
                                (serial_number_size * 2));
    return local_error;
}

int16_t scd4x_perform_self_test(uint16_t* sensor_status) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3639);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10000 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_status = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_perform_factory_reset() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3632);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1200 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_reinit() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3646);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(30 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_get_sensor_variant_raw(uint16_t* sensor_variant) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x202f);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *sensor_variant = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_measure_single_shot() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x219d);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(5000 * 1000);
    return local_error;
}

int16_t scd4x_measure_single_shot_rht_only() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2196);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(50 * 1000);
    return local_error;
}

int16_t scd4x_power_down() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x36e0);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_wake_up() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x36f6);
    sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    sensirion_i2c_hal_sleep_usec(30 * 1000);
    _measurement_running = false;
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_initial_period(
    uint16_t asc_initial_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2445);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_initial_period);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_initial_period(
    uint16_t* asc_initial_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x2340);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_initial_period = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t scd4x_set_automatic_self_calibration_standard_period(
    uint16_t asc_standard_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x244e);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, asc_standard_period);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    return local_error;
}

int16_t scd4x_get_automatic_self_calibration_standard_period(
    uint16_t* asc_standard_period) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x234b);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(1 * 1000);
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *asc_standard_period = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}
